/**
 * ============================================================================
 * PRIMEIRA ONDA EDITORIAL INDEXÁVEL — Rodada 4H
 * ============================================================================
 * Fonte única (build/gates) dos artigos editoriais liberados para indexação.
 * Espelha `APPROVED_EDITORIAL_CONTENT` em `src/lib/blogEditorialRegistry.ts`
 * (paridade validada por `scripts/check-editorial-governance.mjs`).
 *
 * Regras da onda:
 *   • Só entra artigo com revisão técnica concluída (blogEditorialSources.ts),
 *     imagem própria com origem declarada e aprovação editorial datada.
 *   • Todo artigo aqui é indexável, entra no sitemap-editorial.xml e recebe
 *     HTML estático próprio com BlogPosting + BreadcrumbList.
 *   • Qualquer artigo fora desta lista permanece noindex, follow e fora de
 *     todos os sitemaps (fail-closed).
 */

export const EDITORIAL_WAVE = [
  {
    slug: "quando-trocar-hd-por-ssd",
    approvedAt: "2026-08-06",
    pilar: "/servicos/upgrade-ssd-ram",
    pilarLabel: "Upgrade de SSD e memória",
    apoio: "/quando-nao-compensa",
    apoioLabel: "Quando o reparo não compensa",
    cover: "/blog/quando-trocar-hd-por-ssd.jpg",
  },
  {
    slug: "como-saber-se-pc-tem-virus-malware",
    approvedAt: "2026-08-06",
    pilar: "/servicos/remocao-de-virus",
    pilarLabel: "Remoção de vírus e malware",
    apoio: "/servicos/formatacao",
    apoioLabel: "Formatação e instalação do sistema",
    cover: "/blog/como-saber-se-pc-tem-virus-malware.jpg",
  },
  {
    slug: "backup-como-proteger-seus-arquivos",
    approvedAt: "2026-08-06",
    pilar: "/servicos/recuperacao-de-dados",
    pilarLabel: "Recuperação de dados",
    apoio: "/diagnostico-tecnico",
    apoioLabel: "Como funciona o diagnóstico técnico",
    cover: "/blog/backup-como-proteger-seus-arquivos.jpg",
  },
  {
    slug: "como-melhorar-sinal-wifi-em-casa",
    approvedAt: "2026-08-06",
    pilar: "/servicos/redes-e-wifi",
    pilarLabel: "Redes e Wi-Fi",
    apoio: "/atendimento-domicilio",
    apoioLabel: "Atendimento técnico no endereço",
    cover: "/blog/como-melhorar-sinal-wifi-em-casa.jpg",
  },
  {
    slug: "notebook-superaquecendo-o-que-fazer",
    approvedAt: "2026-08-06",
    pilar: "/servicos/manutencao-de-notebook",
    pilarLabel: "Manutenção de notebook em Curitiba",
    apoio: "/atendimento-domicilio",
    apoioLabel: "Atendimento técnico no endereço",
    cover: "/blog/notebook-superaquecendo-o-que-fazer.jpg",
  },
  // ── Rodada 3O — onda educacional empresarial (2 conteúdos, 0 rotas novas).
  {
    slug: "organizacao-de-ti-para-pequenos-escritorios",
    approvedAt: "2026-08-06",
    pilar: "/empresa-de-ti-curitiba",
    pilarLabel: "Empresa de TI em Curitiba",
    apoio: "/servicos/suporte-tecnico-empresarial",
    apoioLabel: "Suporte técnico empresarial",
    cover: "/blog/organizacao-de-ti-para-pequenos-escritorios.jpg",
  },
  {
    slug: "como-escolher-uma-workstation",
    approvedAt: "2026-08-06",
    pilar: "/servicos/montagem-de-pc",
    pilarLabel: "Montagem de PC sob medida",
    apoio: "/servicos/upgrade-ssd-ram",
    apoioLabel: "Upgrade de SSD e memória",
    cover: "/blog/como-escolher-uma-workstation.jpg",
  },
  // ── Rodada 4X — instalação limpa do Windows 11 (capa fotográfica licenciada).
  {
    slug: "como-instalar-windows-11-do-zero",
    approvedAt: "2026-08-12",
    pilar: "/servicos/formatacao",
    pilarLabel: "Formatação e instalação do sistema",
    apoio: "/servicos/recuperacao-de-dados",
    apoioLabel: "Recuperação de dados",
    cover: "/blog/como-instalar-windows-11-do-zero.jpg",
  },
  // ── Rodada 4Y — dois guias herdados reformados (0 rotas novas, capas reais).
  {
    slug: "como-resolver-tela-azul-windows",
    approvedAt: "2026-08-12",
    pilar: "/servicos/manutencao-de-computador",
    pilarLabel: "Manutenção de computador",
    apoio: "/diagnostico-tecnico",
    apoioLabel: "Como funciona o diagnóstico técnico",
    cover: "/blog/como-resolver-tela-azul-windows.jpg",
  },
  {
    slug: "como-trocar-tela-notebook-passo-a-passo",
    approvedAt: "2026-08-12",
    pilar: "/servicos/manutencao-de-notebook",
    pilarLabel: "Manutenção de notebook em Curitiba",
    apoio: "/quando-nao-compensa",
    apoioLabel: "Quando o reparo não compensa",
    cover: "/blog/como-trocar-tela-notebook-passo-a-passo.jpg",
  },
  // ── Rodada 4Z — dois guias herdados de maior volume, mais consolidação
  // de 4 duplicatas por 301 (ver src/lib/redirectMatrix.ts).
  {
    slug: "notebook-nao-liga-o-que-fazer",
    approvedAt: "2026-08-12",
    pilar: "/servicos/manutencao-de-notebook",
    pilarLabel: "Manutenção de notebook em Curitiba",
    apoio: "/diagnostico-tecnico",
    apoioLabel: "Como funciona o diagnóstico técnico",
    cover: "/blog/notebook-nao-liga-o-que-fazer.jpg",
  },
  {
    slug: "computador-lento-causas-solucoes",
    approvedAt: "2026-08-12",
    pilar: "/servicos/manutencao-de-computador",
    pilarLabel: "Manutenção de computador",
    apoio: "/servicos/upgrade-ssd-ram",
    apoioLabel: "Upgrade de SSD e memória",
    cover: "/blog/computador-lento-causas-solucoes.jpg",
  },
  // ── Rodada 5A — dois procedimentos técnicos herdados reescritos do zero
  // (texto-modelo e marca de origem removidos), com capas fotográficas reais.
  {
    slug: "como-recuperar-dados-hd-com-defeito",
    approvedAt: "2026-08-12",
    pilar: "/servicos/recuperacao-de-dados",
    pilarLabel: "Recuperação de dados",
    apoio: "/diagnostico-tecnico",
    apoioLabel: "Como funciona o diagnóstico técnico",
    cover: "/blog/como-recuperar-dados-hd-com-defeito.jpg",
  },
  {
    slug: "como-fazer-upgrade-ssd-nvme",
    approvedAt: "2026-08-12",
    pilar: "/servicos/upgrade-ssd-ram",
    pilarLabel: "Upgrade de SSD e memória",
    apoio: "/servicos/formatacao",
    apoioLabel: "Formatação e instalação do sistema",
    cover: "/blog/como-fazer-upgrade-ssd-nvme.jpg",
  },
  // ── Rodada 5B — cluster de redes Wi-Fi doméstica.
  {
    slug: "como-configurar-roteador-wifi-iniciantes",
    approvedAt: "2026-08-12",
    pilar: "/servicos/redes-e-wifi",
    pilarLabel: "Configuração de redes e Wi-Fi",
    apoio: "/blog/como-melhorar-sinal-wifi-em-casa",
    apoioLabel: "Como melhorar o sinal de Wi-Fi em casa",
    cover: "/blog/como-configurar-roteador-wifi-iniciantes.jpg",
  },
  {
    slug: "como-saber-quem-esta-usando-meu-wifi",
    approvedAt: "2026-08-12",
    pilar: "/servicos/redes-e-wifi",
    pilarLabel: "Configuração de redes e Wi-Fi",
    apoio: "/blog/como-configurar-roteador-wifi-iniciantes",
    apoioLabel: "Como configurar um roteador do zero",
    cover: "/blog/como-saber-quem-esta-usando-meu-wifi.jpg",
  },
  // ── Rodada 5C — cluster de segurança (antivírus e golpes on-line).
  {
    slug: "como-escolher-um-bom-antivirus",
    approvedAt: "2026-08-12",
    pilar: "/servicos/remocao-de-virus",
    pilarLabel: "Remoção de vírus e malware",
    apoio: "/servicos/formatacao",
    apoioLabel: "Formatação e instalação do sistema",
    cover: "/blog/como-escolher-um-bom-antivirus.jpg",
  },
  {
    slug: "como-proteger-computador-golpes-internet",
    approvedAt: "2026-08-12",
    pilar: "/servicos/remocao-de-virus",
    pilarLabel: "Remoção de vírus e malware",
    apoio: "/servicos/recuperacao-de-dados",
    apoioLabel: "Recuperação de dados",
    cover: "/blog/como-proteger-computador-golpes-internet.jpg",
  },
  // ── Rodada 5D — manutenção física de notebook (limpeza interna e pasta térmica).
  {
    slug: "como-limpar-notebook-por-dentro",
    approvedAt: "2026-08-12",
    pilar: "/servicos/manutencao-de-notebook",
    pilarLabel: "Manutenção de notebook em Curitiba",
    apoio: "/blog/notebook-superaquecendo-o-que-fazer",
    apoioLabel: "Notebook superaquecendo: o que fazer",
    cover: "/blog/como-limpar-notebook-por-dentro.jpg",
  },
  {
    slug: "como-trocar-pasta-termica-notebook",
    approvedAt: "2026-08-12",
    pilar: "/servicos/manutencao-de-notebook",
    pilarLabel: "Manutenção de notebook em Curitiba",
    apoio: "/blog/como-limpar-notebook-por-dentro",
    apoioLabel: "Limpeza interna de notebook",
    cover: "/blog/como-trocar-pasta-termica-notebook.jpg",
  },
  // ── Rodada 5E — armazenamento (clonagem e segundo disco).
  {
    slug: "como-clonar-hd-para-ssd",
    approvedAt: "2026-08-12",
    pilar: "/servicos/upgrade-ssd-ram",
    pilarLabel: "Upgrade de SSD e memória em Curitiba",
    apoio: "/blog/como-fazer-upgrade-ssd-nvme",
    apoioLabel: "Upgrade para SSD NVMe",
    cover: "/blog/como-clonar-hd-para-ssd.jpg",
  },
  {
    slug: "como-instalar-segundo-ssd-notebook",
    approvedAt: "2026-08-12",
    pilar: "/servicos/upgrade-ssd-ram",
    pilarLabel: "Upgrade de SSD e memória em Curitiba",
    apoio: "/blog/como-clonar-hd-para-ssd",
    apoioLabel: "Clonar HD para SSD",
    cover: "/blog/como-instalar-segundo-ssd-notebook.jpg",
  },
  // ── Rodada 5F — continuidade empresarial (ransomware e backup em nuvem).
  {
    slug: "ransomware-como-proteger-empresa",
    approvedAt: "2026-08-12",
    pilar: "/servicos/backup-para-empresas",
    pilarLabel: "Backup para empresas em Curitiba",
    apoio: "/blog/backup-nuvem-empresas-qual-escolher",
    apoioLabel: "Backup em nuvem para empresas",
    cover: "/blog/ransomware-como-proteger-empresa.jpg",
  },
  {
    slug: "backup-nuvem-empresas-qual-escolher",
    approvedAt: "2026-08-12",
    pilar: "/servicos/backup-para-empresas",
    pilarLabel: "Backup para empresas em Curitiba",
    apoio: "/blog/ransomware-como-proteger-empresa",
    apoioLabel: "Ransomware em pequenas empresas",
    cover: "/blog/backup-nuvem-empresas-qual-escolher.jpg",
  },
  // ── Rodada 5G — impressora em rede e Smart TV no Wi-Fi.
  {
    slug: "como-instalar-impressora-windows-passo-a-passo",
    approvedAt: "2026-08-12",
    pilar: "/servicos/redes-e-wifi",
    pilarLabel: "Redes e Wi-Fi em Curitiba",
    apoio: "/blog/como-configurar-roteador-wifi-iniciantes",
    apoioLabel: "Configurar roteador Wi-Fi do zero",
    cover: "/blog/como-instalar-impressora-windows-passo-a-passo.jpg",
  },
  {
    slug: "como-conectar-wifi-tv-nao-conecta",
    approvedAt: "2026-08-12",
    pilar: "/servicos/conserto-tv",
    pilarLabel: "Conserto de TV em Curitiba",
    apoio: "/blog/como-instalar-impressora-windows-passo-a-passo",
    apoioLabel: "Impressora em rede: por que ela some",
    cover: "/blog/como-conectar-wifi-tv-nao-conecta.jpg",
  },
  // ── Rodada 5H — energia e placa-mãe (diagnóstico de bancada).
  {
    slug: "como-testar-fonte-de-alimentacao-pc",
    approvedAt: "2026-08-12",
    pilar: "/servicos/computador-nao-liga",
    pilarLabel: "Computador não liga em Curitiba",
    apoio: "/blog/como-diagnosticar-placa-mae-defeituosa",
    apoioLabel: "Placa-mãe defeituosa: como confirmar",
    cover: "/blog/como-testar-fonte-de-alimentacao-pc.jpg",
  },
  {
    slug: "como-diagnosticar-placa-mae-defeituosa",
    approvedAt: "2026-08-12",
    pilar: "/servicos/conserto-placa",
    pilarLabel: "Conserto de placa em Curitiba",
    apoio: "/blog/como-testar-fonte-de-alimentacao-pc",
    apoioLabel: "Testar a fonte do PC sem trocar peça boa",
    cover: "/blog/como-diagnosticar-placa-mae-defeituosa.jpg",
  },
  // ── Rodada 5I — desempenho do Windows e remoção de malware.
  {
    slug: "windows-11-lento-como-resolver",
    approvedAt: "2026-08-12",
    pilar: "/servicos/formatacao",
    pilarLabel: "Formatação e otimização em Curitiba",
    apoio: "/blog/como-remover-virus-windows-iniciantes",
    apoioLabel: "Remover vírus e adware sem quebrar o sistema",
    cover: "/blog/windows-11-lento-como-resolver.jpg",
  },
  {
    slug: "como-remover-virus-windows-iniciantes",
    approvedAt: "2026-08-12",
    pilar: "/servicos/remocao-de-virus",
    pilarLabel: "Remoção de vírus em Curitiba",
    apoio: "/blog/windows-11-lento-como-resolver",
    apoioLabel: "Windows 11 lento: achar a causa real",
    cover: "/blog/como-remover-virus-windows-iniciantes.jpg",
  },
  // ── Rodada 8E — cluster piloto formatação (informacional + comercial).
  {
    slug: "como-formatar-pc-sem-perder-arquivos",
    approvedAt: "2026-08-14",
    pilar: "/servicos/formatacao",
    pilarLabel: "Formatação e instalação do sistema",
    apoio: "/blog/quanto-custa-formatar-um-computador",
    apoioLabel: "Quanto custa formatar um computador",
    cover: "/blog/como-formatar-pc-sem-perder-arquivos.jpg",
  },
  {
    slug: "quanto-custa-formatar-um-computador",
    approvedAt: "2026-08-14",
    pilar: "/servicos/formatacao",
    pilarLabel: "Formatação e instalação do sistema",
    apoio: "/blog/como-formatar-pc-sem-perder-arquivos",
    apoioLabel: "Formatar sem perder arquivos: o guia",
    cover: "/blog/quanto-custa-formatar-um-computador.jpg",
  },

  // ── Rodada 9B — pilares nacionais de autoridade editorial (fundamentos).
  {
    slug: "o-que-e-informatica",
    approvedAt: "2026-08-15",
    pilar: "/blog",
    pilarLabel: "Hub de guias técnicos",
    apoio: "/blog/informatica-basica",
    apoioLabel: "Informática básica",
    cover: "/blog/o-que-e-informatica.jpg",
  },
  {
    slug: "informatica-basica",
    approvedAt: "2026-08-15",
    pilar: "/blog",
    pilarLabel: "Hub de guias técnicos",
    apoio: "/blog/como-aprender-informatica",
    apoioLabel: "Como aprender informática",
    cover: "/blog/informatica-basica.jpg",
  },
  {
    slug: "como-aprender-informatica",
    approvedAt: "2026-08-15",
    pilar: "/blog",
    pilarLabel: "Hub de guias técnicos",
    apoio: "/blog/o-que-e-informatica",
    apoioLabel: "O que é informática",
    cover: "/blog/como-aprender-informatica.jpg",
  },

  // ── Rodada 9C — cluster "computador entra direto na BIOS".
  {
    slug: "computador-entra-direto-na-bios",
    approvedAt: "2026-08-25",
    pilar: "/servicos/manutencao-de-computador",
    pilarLabel: "Manutenção e conserto de computador",
    apoio: "/blog/erro-no-bootable-device-como-resolver",
    apoioLabel: 'Erro "No Bootable Device": como resolver',
    cover: "/blog/computador-entra-direto-na-bios.jpg",
  },
  {
    slug: "erro-no-bootable-device-como-resolver",
    approvedAt: "2026-08-25",
    pilar: "/diagnostico-tecnico",
    pilarLabel: "Diagnóstico técnico",
    apoio: "/blog/computador-entra-direto-na-bios",
    apoioLabel: "Computador entra direto na BIOS",
    cover: "/blog/erro-no-bootable-device-como-resolver.jpg",
  },
  {
    slug: "troquei-o-ssd-e-o-pc-so-abre-a-bios",
    approvedAt: "2026-08-25",
    pilar: "/servicos/upgrade-ssd-ram",
    pilarLabel: "Upgrade de SSD e memória",
    apoio: "/blog/computador-entra-direto-na-bios",
    apoioLabel: "Computador entra direto na BIOS",
    cover: "/blog/troquei-o-ssd-e-o-pc-so-abre-a-bios.jpg",
  },

  // ── Onda 10C — satélites de lentidão extrema e tela azul.
  {
    slug: "limpar-arquivos-temporarios-windows",
    approvedAt: "2026-08-25",
    pilar: "/blog/computador-lento-causas-solucoes",
    pilarLabel: "Computador lento: causas e soluções",
    apoio: "/blog/memoria-ram-insuficiente-sintomas",
    apoioLabel: "Memória RAM insuficiente: sintomas",
    cover: "/blog/limpar-arquivos-temporarios-windows.jpg",
  },
  {
    slug: "memoria-ram-insuficiente-sintomas",
    approvedAt: "2026-08-25",
    pilar: "/servicos/upgrade-ssd-ram",
    pilarLabel: "Upgrade de SSD e memória",
    apoio: "/blog/testar-memoria-ram-memtest86",
    apoioLabel: "Testar a memória RAM com Memtest86+",
    cover: "/blog/memoria-ram-insuficiente-sintomas.jpg",
  },
  {
    slug: "codigos-de-erro-tela-azul-windows",
    approvedAt: "2026-08-25",
    pilar: "/blog/como-resolver-tela-azul-windows",
    pilarLabel: "Como resolver a tela azul do Windows",
    apoio: "/blog/testar-memoria-ram-memtest86",
    apoioLabel: "Testar a memória RAM com Memtest86+",
    cover: "/blog/codigos-de-erro-tela-azul-windows.jpg",
  },
  {
    slug: "testar-memoria-ram-memtest86",
    approvedAt: "2026-08-25",
    pilar: "/diagnostico-tecnico",
    pilarLabel: "Diagnóstico técnico",
    apoio: "/blog/codigos-de-erro-tela-azul-windows",
    apoioLabel: "Códigos de erro da tela azul",
    cover: "/blog/testar-memoria-ram-memtest86.jpg",
  },

  // ── Onda 10D — satélites de "PC não liga" e "liga e desliga sozinho".
  {
    slug: "botao-power-nao-funciona-jump-start-placa-mae",
    approvedAt: "2026-08-26",
    pilar: "/servicos/manutencao-de-computador",
    pilarLabel: "Conserto de computador",
    apoio: "/blog/como-testar-fonte-de-alimentacao-pc",
    apoioLabel: "Como testar a fonte de alimentação",
    cover: "/blog/botao-power-nao-funciona-jump-start-placa-mae.jpg",
  },
  {
    slug: "curto-circuito-placa-mae-como-identificar",
    approvedAt: "2026-08-26",
    pilar: "/diagnostico-tecnico",
    pilarLabel: "Diagnóstico técnico",
    apoio: "/blog/como-diagnosticar-placa-mae-defeituosa",
    apoioLabel: "Como diagnosticar placa-mãe defeituosa",
    cover: "/blog/curto-circuito-placa-mae-como-identificar.jpg",
  },
  {
    slug: "bios-corrompida-reset-cmos-atualizacao",
    approvedAt: "2026-08-26",
    pilar: "/blog/computador-entra-direto-na-bios",
    pilarLabel: "Computador entra direto na BIOS",
    apoio: "/blog/curto-circuito-placa-mae-como-identificar",
    apoioLabel: "Curto-circuito na placa-mãe",
    cover: "/blog/bios-corrompida-reset-cmos-atualizacao.jpg",
  },
  // Onda 10C — Lote 2: internet/Wi-Fi (triagem) e impressoras.
  {
    slug: "internet-lenta-provedor-ou-roteador",
    approvedAt: "2026-08-26",
    pilar: "/servicos/redes-e-wifi",
    pilarLabel: "Redes e Wi-Fi",
    apoio: "/blog/como-melhorar-sinal-wifi-em-casa",
    apoioLabel: "Como melhorar o sinal de Wi-Fi em casa",
    cover: "/blog/internet-lenta-provedor-ou-roteador.jpg",
  },
  {
    slug: "impressora-offline-como-resolver",
    approvedAt: "2026-08-26",
    pilar: "/servicos/redes-e-wifi",
    pilarLabel: "Redes e Wi-Fi",
    apoio: "/blog/como-instalar-impressora-windows-passo-a-passo",
    apoioLabel: "Como instalar impressora no Windows",
    cover: "/blog/impressora-offline-como-resolver.jpg",
  },
  {
    slug: "fila-de-impressao-travada-spooler-windows",
    approvedAt: "2026-08-26",
    pilar: "/diagnostico-tecnico",
    pilarLabel: "Diagnóstico técnico",
    apoio: "/blog/impressora-offline-como-resolver",
    apoioLabel: "Impressora offline: como resolver",
    cover: "/blog/fila-de-impressao-travada-spooler-windows.jpg",
  },
  // Onda 10C — Lote 3: armazenamento não detectado e áudio sem som.
  {
    slug: "hd-nao-e-reconhecido-na-bios-o-que-fazer",
    approvedAt: "2026-08-26",
    pilar: "/servicos/recuperacao-de-dados",
    pilarLabel: "Recuperação de dados",
    apoio: "/blog/ssd-nvme-nao-aparece-no-gerenciador-de-discos",
    apoioLabel: "SSD não aparece no Gerenciador de Discos",
    cover: "/blog/hd-nao-e-reconhecido-na-bios-o-que-fazer.jpg",
  },
  {
    slug: "ssd-nvme-nao-aparece-no-gerenciador-de-discos",
    approvedAt: "2026-08-26",
    pilar: "/servicos/upgrade-ssd-ram",
    pilarLabel: "Upgrade de SSD e memória",
    apoio: "/blog/hd-nao-e-reconhecido-na-bios-o-que-fazer",
    apoioLabel: "Disco não reconhecido na BIOS",
    cover: "/blog/ssd-nvme-nao-aparece-no-gerenciador-de-discos.jpg",
  },
  {
    slug: "disco-com-setores-defeituosos-smart-o-que-fazer",
    approvedAt: "2026-08-26",
    pilar: "/servicos/recuperacao-de-dados",
    pilarLabel: "Recuperação de dados",
    apoio: "/blog/como-recuperar-dados-hd-com-defeito",
    apoioLabel: "Como recuperar dados de HD com defeito",
    cover: "/blog/disco-com-setores-defeituosos-smart-o-que-fazer.jpg",
  },
  {
    slug: "computador-sem-som-o-que-verificar",
    approvedAt: "2026-08-26",
    pilar: "/servicos/manutencao-de-computador",
    pilarLabel: "Manutenção de computador",
    apoio: "/blog/servico-de-audio-do-windows-nao-esta-em-execucao",
    apoioLabel: "Serviço de áudio do Windows parado",
    cover: "/blog/computador-sem-som-o-que-verificar.jpg",
  },
  {
    slug: "fone-de-ouvido-nao-e-reconhecido-no-pc",
    approvedAt: "2026-08-26",
    pilar: "/servicos/manutencao-de-computador",
    pilarLabel: "Manutenção de computador",
    apoio: "/blog/computador-sem-som-o-que-verificar",
    apoioLabel: "Computador sem som: o que verificar",
    cover: "/blog/fone-de-ouvido-nao-e-reconhecido-no-pc.jpg",
  },
  {
    slug: "servico-de-audio-do-windows-nao-esta-em-execucao",
    approvedAt: "2026-08-26",
    pilar: "/diagnostico-tecnico",
    pilarLabel: "Diagnóstico técnico",
    apoio: "/blog/computador-sem-som-o-que-verificar",
    apoioLabel: "Computador sem som: o que verificar",
    cover: "/blog/servico-de-audio-do-windows-nao-esta-em-execucao.jpg",
  },
  {
    slug: "webcam-nao-funciona-o-que-verificar",
    approvedAt: "2026-08-26",
    pilar: "/diagnostico-tecnico",
    pilarLabel: "Diagnóstico técnico",
    apoio: "/blog/permissoes-de-camera-no-windows",
    apoioLabel: "Permissões de câmera no Windows",
    cover: "/blog/webcam-nao-funciona-o-que-verificar.jpg",
  },
  {
    slug: "permissoes-de-camera-no-windows",
    approvedAt: "2026-08-26",
    pilar: "/diagnostico-tecnico",
    pilarLabel: "Diagnóstico técnico",
    apoio: "/blog/webcam-nao-funciona-o-que-verificar",
    apoioLabel: "Webcam não funciona: o que verificar",
    cover: "/blog/permissoes-de-camera-no-windows.jpg",
  },
  {
    slug: "webcam-usb-nao-e-detectada",
    approvedAt: "2026-08-26",
    pilar: "/servicos/manutencao-de-computador",
    pilarLabel: "Manutenção de computador",
    apoio: "/blog/webcam-nao-funciona-o-que-verificar",
    apoioLabel: "Webcam não funciona: o que verificar",
    cover: "/blog/webcam-usb-nao-e-detectada.jpg",
  },
  {
    slug: "windows-update-nao-funciona-o-que-verificar",
    approvedAt: "2026-08-26",
    pilar: "/diagnostico-tecnico",
    pilarLabel: "Diagnóstico técnico",
    apoio: "/blog/limpar-cache-do-windows-update-softwaredistribution",
    apoioLabel: "Cache do Windows Update",
    cover: "/blog/windows-update-nao-funciona-o-que-verificar.jpg",
  },
  {
    slug: "limpar-cache-do-windows-update-softwaredistribution",
    approvedAt: "2026-08-26",
    pilar: "/servicos/manutencao-de-computador",
    pilarLabel: "Manutenção de computador",
    apoio: "/blog/windows-update-nao-funciona-o-que-verificar",
    apoioLabel: "Windows Update não funciona",
    cover: "/blog/limpar-cache-do-windows-update-softwaredistribution.jpg",
  },
  {
    slug: "windows-update-travado-desfazendo-alteracoes",
    approvedAt: "2026-08-26",
    pilar: "/diagnostico-tecnico",
    pilarLabel: "Diagnóstico técnico",
    apoio: "/blog/windows-update-nao-funciona-o-que-verificar",
    apoioLabel: "Windows Update não funciona",
    cover: "/blog/windows-update-travado-desfazendo-alteracoes.jpg",
  },
  {
    slug: "boot-uefi-ou-legacy-como-identificar",
    approvedAt: "2026-08-31",
    pilar: "/diagnostico-tecnico",
    pilarLabel: "Diagnóstico técnico",
    apoio: "/blog/ordem-de-boot-na-bios-como-configurar",
    apoioLabel: "Ordem de boot na BIOS",
    cover: "/blog/boot-uefi-ou-legacy-como-identificar.jpg",
  },
  {
    slug: "ordem-de-boot-na-bios-como-configurar",
    approvedAt: "2026-08-31",
    pilar: "/diagnostico-tecnico",
    pilarLabel: "Diagnóstico técnico",
    apoio: "/blog/boot-uefi-ou-legacy-como-identificar",
    apoioLabel: "UEFI ou Legacy: como identificar",
    cover: "/blog/ordem-de-boot-na-bios-como-configurar.jpg",
  },
  {
    slug: "windows-reparo-automatico-em-loop",
    approvedAt: "2026-08-31",
    pilar: "/servicos/manutencao-de-computador",
    pilarLabel: "Manutenção de computador",
    apoio: "/blog/boot-uefi-ou-legacy-como-identificar",
    apoioLabel: "UEFI ou Legacy: como identificar",
    cover: "/blog/windows-reparo-automatico-em-loop.jpg",
  },
  {
    slug: "manutencao-preventiva-de-computador-guia-completo",
    approvedAt: "2026-09-03",
    pilar: "/servicos/manutencao-de-computador",
    pilarLabel: "Manutenção de computador",
    apoio: "/blog/como-limpar-notebook-por-dentro",
    apoioLabel: "Como limpar o notebook por dentro",
    cover: "/blog/manutencao-preventiva-de-computador-guia-completo.jpg",
  },
  {
    slug: "dispositivo-usb-nao-reconhecido-o-que-fazer",
    approvedAt: "2026-09-03",
    pilar: "/diagnostico-tecnico",
    pilarLabel: "Diagnóstico técnico",
    apoio: "/blog/webcam-usb-nao-e-detectada",
    apoioLabel: "Webcam USB não é detectada",
    cover: "/blog/dispositivo-usb-nao-reconhecido-o-que-fazer.jpg",
  },
  {
    slug: "como-testar-restauracao-de-backup",
    approvedAt: "2026-09-03",
    pilar: "/servicos/backup-para-empresas",
    pilarLabel: "Backup para empresas",
    apoio: "/decisoes/nuvem-ou-hd-externo",
    apoioLabel: "Nuvem ou HD externo",
    cover: "/blog/como-testar-restauracao-de-backup.jpg",
  },
  // ── Onda 11D — térmica, mídia removível e versionamento de arquivos.
  {
    slug: "como-monitorar-temperatura-do-computador",
    approvedAt: "2026-09-03",
    pilar: "/servicos/manutencao-de-computador",
    pilarLabel: "Manutenção de computador",
    apoio: "/blog/notebook-superaquecendo-o-que-fazer",
    apoioLabel: "Notebook superaquecendo",
    cover: "/blog/como-monitorar-temperatura-do-computador.jpg",
  },
  {
    slug: "pendrive-somente-leitura-protegido-contra-gravacao",
    approvedAt: "2026-09-03",
    pilar: "/diagnostico-tecnico",
    pilarLabel: "Diagnóstico técnico",
    apoio: "/blog/dispositivo-usb-nao-reconhecido-o-que-fazer",
    apoioLabel: "Dispositivo USB não reconhecido",
    cover: "/blog/pendrive-somente-leitura-protegido-contra-gravacao.jpg",
  },
  {
    slug: "historico-de-arquivos-windows-como-configurar",
    approvedAt: "2026-09-03",
    pilar: "/servicos/backup-para-empresas",
    pilarLabel: "Backup para empresas",
    apoio: "/blog/como-testar-restauracao-de-backup",
    apoioLabel: "Como testar se o backup funciona",
    cover: "/blog/historico-de-arquivos-windows-como-configurar.jpg",
  },
  // ── Onda 11E — vídeo, energia de notebook e migração de arquivos.
  {
    slug: "monitor-sem-sinal-o-que-verificar",
    approvedAt: "2026-09-03",
    pilar: "/diagnostico-tecnico",
    pilarLabel: "Diagnóstico técnico",
    apoio: "/blog/como-diagnosticar-placa-mae-defeituosa",
    apoioLabel: "Diagnóstico de placa-mãe",
    cover: "/blog/monitor-sem-sinal-o-que-verificar.jpg",
  },
  {
    slug: "bateria-de-notebook-nao-carrega-o-que-verificar",
    approvedAt: "2026-09-03",
    pilar: "/servicos/manutencao-de-computador",
    pilarLabel: "Manutenção de computador",
    apoio: "/blog/notebook-superaquecendo-o-que-fazer",
    apoioLabel: "Notebook superaquecendo",
    cover: "/blog/bateria-de-notebook-nao-carrega-o-que-verificar.jpg",
  },
  {
    slug: "como-migrar-arquivos-para-um-computador-novo",
    approvedAt: "2026-09-03",
    pilar: "/servicos/backup-para-empresas",
    pilarLabel: "Backup para empresas",
    apoio: "/blog/historico-de-arquivos-windows-como-configurar",
    apoioLabel: "Histórico de Arquivos do Windows",
    cover: "/blog/como-migrar-arquivos-para-um-computador-novo.jpg",
  },
  // ── Onda 11F — teclado de notebook, desligamento repentino e rede cabeada.
  {
    slug: "teclado-de-notebook-nao-funciona-o-que-verificar",
    approvedAt: "2026-09-03",
    pilar: "/servicos/manutencao-de-notebook",
    pilarLabel: "Manutenção de notebook",
    apoio: "/blog/como-limpar-notebook-por-dentro",
    apoioLabel: "Limpeza interna do notebook",
    cover: "/blog/teclado-de-notebook-nao-funciona-o-que-verificar.jpg",
  },
  {
    slug: "computador-desliga-sozinho-o-que-verificar",
    approvedAt: "2026-09-03",
    pilar: "/servicos/manutencao-de-computador",
    pilarLabel: "Manutenção de computador",
    apoio: "/blog/como-testar-fonte-de-alimentacao-pc",
    apoioLabel: "Como testar a fonte de alimentação",
    cover: "/blog/computador-desliga-sozinho-o-que-verificar.jpg",
  },
  {
    slug: "computador-nao-conecta-na-internet-por-cabo",
    approvedAt: "2026-09-03",
    pilar: "/servicos/redes-e-wifi",
    pilarLabel: "Redes e Wi-Fi",
    apoio: "/blog/internet-lenta-provedor-ou-roteador",
    apoioLabel: "Internet lenta: provedor ou roteador",
    cover: "/blog/computador-nao-conecta-na-internet-por-cabo.jpg",
  },
  // ── Onda 11G — ruído de ventoinha, rede Wi-Fi ausente e arquivo corrompido.
  {
    slug: "ventoinha-do-computador-fazendo-barulho-o-que-verificar",
    approvedAt: "2026-09-03",
    pilar: "/servicos/manutencao-de-computador",
    pilarLabel: "Manutenção de computador",
    apoio: "/blog/manutencao-preventiva-de-computador-guia-completo",
    apoioLabel: "Manutenção preventiva de computador",
    cover: "/blog/ventoinha-do-computador-fazendo-barulho-o-que-verificar.jpg",
  },
  {
    slug: "rede-wifi-nao-aparece-na-lista-o-que-verificar",
    approvedAt: "2026-09-03",
    pilar: "/servicos/redes-e-wifi",
    pilarLabel: "Redes e Wi-Fi",
    apoio: "/blog/como-configurar-roteador-wifi-iniciantes",
    apoioLabel: "Como configurar o roteador Wi-Fi",
    cover: "/blog/rede-wifi-nao-aparece-na-lista-o-que-verificar.jpg",
  },
  {
    slug: "arquivo-corrompido-nao-abre-o-que-fazer",
    approvedAt: "2026-09-03",
    pilar: "/servicos/recuperacao-de-dados",
    pilarLabel: "Recuperação de dados",
    apoio: "/blog/como-recuperar-dados-hd-com-defeito",
    apoioLabel: "Recuperação de dados em HD com defeito",
    cover: "/blog/arquivo-corrompido-nao-abre-o-que-fazer.jpg",
  },
];


export const EDITORIAL_WAVE_SLUGS = EDITORIAL_WAVE.map((a) => a.slug);

const BY_SLUG = new Map(EDITORIAL_WAVE.map((a) => [a.slug, a]));

export function getWaveArticle(slug) {
  return BY_SLUG.get(slug);
}

export function isWaveApproved(slug) {
  return BY_SLUG.has(slug);
}
