// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const CONFIGURED_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim();
const CONFIGURED_SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();

const SUPABASE_CONFIGURED = Boolean(
  CONFIGURED_SUPABASE_URL && CONFIGURED_SUPABASE_PUBLISHABLE_KEY,
);

// Valores inertes permitem importar/listar/testar o frontend sem qualquer chave.
// O fetch abaixo bloqueia rede quando a integração não está configurada.
const SUPABASE_URL = CONFIGURED_SUPABASE_URL || 'http://127.0.0.1:54321';
const SUPABASE_PUBLISHABLE_KEY = CONFIGURED_SUPABASE_PUBLISHABLE_KEY || 'disabled';


function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  if (!SUPABASE_CONFIGURED) {
    return async () =>
      new Response(JSON.stringify({ message: 'External data service is not configured.' }), {
        status: 503,
        headers: { 'content-type': 'application/json' },
      });
  }

  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
  },
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
